### ISSUE TITLE
Please update documentation to reflect new language directions

### ISSUE THREAD

**Issue by Bujiraso** [aliceinit/todocycle#3]
This project is changing implementation from Python to NodeJS, from PostgreSQL to MongoDB.
Please update all relevant documentation.

Also please look into how I can be given push or write access to this repo, as a contributor, so I can assist in making changes. My fork will essentially be a temporary, transitional, or trash branch storage, as I plan to make most changes directly to this repo.

**Comment by aliceinit** [comment]
Invite for push access has been sent and docs are updated. Thanks!
